def resolve_math_past_paper_data(obj, info, apikey):
    print("resolve_math_past_paper_data")
    payload = [
        {
            "id":1,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2014,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":2,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2014,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":3,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2014,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":4,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2014,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":5,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2014,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":6,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2014,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":7,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2014,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":8,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2014,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":9,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2015,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":10,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2015,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":11,
            "name":"Mathematics Paper2  ",
            "subject":"Mathematics",
            "paper":2,
            "year":2015,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":12,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2015,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":13,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2015,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":14,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2015,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":15,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2015,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":16,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2015,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":17,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2016,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":18,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2016,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":19,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2016,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":20,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2016,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":21,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2016,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":22,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2016,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":23,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2016,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":24,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2016,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":25,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2017,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":26,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2017,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":27,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2017,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":28,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2017,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":29,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2017,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":30,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2017,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":31,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2017,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":32,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2017,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":33,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2018,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":34,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2018,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":35,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2018,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":36,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2018,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":37,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2018,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":38,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2018,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":39,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2018,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":40,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2018,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":41,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2019,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":42,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2019,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":43,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2019,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":44,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2019,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":45,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2019,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":46,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2019,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":47,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2019,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":48,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2019,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":49,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2020,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":50,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2020,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":51,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2020,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":52,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2020,
            "grade":12,
            "month":"June",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":53,
            "name":"Paper 1 Question Paper",
            "subject":"Mathematics",
            "paper":1,
            "year":2020,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":54,
            "name":"Paper 1 Memo",
            "subject":"Mathematics",
            "paper":1,
            "year":2020,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":55,
            "name":"Paper 2 Question Paper",
            "subject":"Mathematics",
            "paper":2,
            "year":2020,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        },
        {
            "id":56,
            "name":"Paper 2 Memo",
            "subject":"Mathematics",
            "paper":2,
            "year":2020,
            "grade":12,
            "month":"November",
            "curriculum":"NSC",
            "country":"South Africa",
            "language":"English"
        }
    ]
    return payload