# This is a basic workflow to help you get started with Actions

# name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main, release/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3
      
#         name: Install and set flutter version
#       - uses: actions/checkout@v3
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable' # or: 'beta' or 'master'
#       - run: cd packages/client && flutter --version && cd ../..
      
#         name: Restore Flutter Packages
#       - run: cd packages/client && flutter pub get && cd ../..
      
#         name: Analyze Flutter Code
#       - run: cd packages/client && flutter analyze && cd ../..
      
#         name: Run Tests
#       - run: cd packages/client && flutter test --coverage && cd ../..
      
#         name: Upload coverage to codecov
#       - run: cd packages/client && curl -s https://codecov.io/bash && cd ../..
#       - shell: bash
